# Generated by Django 4.2.7 on 2023-11-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_budget', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('IT', 'IT'), ('Marketing', 'Marketing'), ('Sales', 'Sales')], max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('invoice_image', models.ImageField(upload_to='invoices/')),
                ('invoice_type', models.CharField(choices=[('Hardware and Infrastructure', 'Hardware and Infrastructure'), ('Software and Licensing Fees', 'Software and Licensing Fees'), ('Support and Training', 'Support and Training'), ('Advertising and Media Buying', 'Advertising and Media Buying'), ('Promotional Activities', 'Promotional Activities'), ('Training and Development', 'Training and Development'), ('Travel and Transportation', 'Travel and Transportation'), ('Digital Sales Resources', 'Digital Sales Resources'), ('Equipment and Supplies', 'Equipment and Supplies')], max_length=100)),
            ],
        ),
    ]
