# Generated by Django 4.2.7 on 2023-11-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_invoice_invoice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_image',
            field=models.ImageField(upload_to='invoices/'),
        ),
    ]
