# Generated by Django 4.2.7 on 2023-12-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_invoice_invoice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
